### PR TITLE
Bennie

### PR DESCRIPTION
**Pull request by benniedraaijer**
@taipo1 taipo Please ignore de JS FILES

### CODE REVIEW

**Comment by benniedraaijer** [comment]
@taipo1 


ready for merge

15c94af

b471493

d89e084

bd0641a

**Comment by benniedraaijer** [comment]
Ignore
bf7e034
09f7ace
f463313
e4fca9a
3bc58ea

**Comment by taipo1** [comment]
Plz update your local script.test before repushing your brange to master

**Comment by taipo1** [comment]
pls update your script.test so this conflict can be resolved

**Pull request closed without merging**
